# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Project.destroy_all
Organization.destroy_all
# organizations attributes :id,:name,:category, :description, :email,:phone,:mission,:location,:image,:website,:twitter,:instagram,:facebook,:logo
# attributes :id,:name,:description,:expectations,:timeline,:team_size,:organization
organizations = [
    {name: "digitalundivided", category: "community improvement", mission: "To use innovation to create system change by catalyzing economic growth for Black and Latinx communities through women entrepreneurs.", location: "Newark Hahne Building 625 Broad Street Newark, NJ 07102 Atlanta Hurt Building 50 Hurt Plaza SE Atlanta, GA 30306", logo: "https://images.squarespace-cdn.com/content/v1/5e2613fbf9e62c2c012e80e3/1581327262914-PAI6JNUZS8G8RQDT742X/ke17ZwdGBToddI8pDm48kLkXF2pIyv_F2eUT9F60jBl7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z4YTzHvnKhyp6Da-NYroOW3ZGjoBKy3azqku80C789l0iyqMbMesKd95J-X4EagrgU9L3Sa3U8cogeb0tjXbfawd0urKshkc5MgdBeJmALQKw/WWN-In-Between-K%2BT-7846.jpg?format=1500w", website: "https://www.digitalundivided.com/"},
    {name: "Women’s Housing and Economic Development Corporation (WHEDco)", category: "community improvement", mission: "WHEDco’s mission is to give the South Bronx access to all the resources that create thriving neighborhoods: from high-quality early education and after-school programs, to fresh, healthy food, cultural programming, and economic opportunity.", location: "50 E 168th St, The Bronx, NY 10452", logo: "https://secureservercdn.net/50.62.88.95/85f.ca5.myftpupload.com/wp-content/uploads/2016/08/Afterschool-2.jpg", website: "https://whedco.org/", twitter: "https://twitter.com/WHEDcoSpeaks", facebook: "https://www.facebook.com/WHEDco/"},
    {name: "Northern Manhattan Improvement Corporation (NMIC)", category: "community improvement", mission: "Our mission is to serve as a catalyst for positive change in the lives of the people in our community on their paths to secure and prosperous futures.", location: "45 Wadsworth Avenue, New York, NY 10033 / 8 Clinton Place, Bronx, NY  10453", website: "https://www.nmic.org/", twitter: "https://twitter.com/NMICNYC"},
    {name: "Fifth Avenue Committee", category: "community improvement", mission: "Fifth Avenue Committee, Inc. (FAC) is a community organization in South Brooklyn that advances economic and social justice by building vibrant, diverse communities where residents have genuine opportunities to achieve their goals, as well as the power to shape the community’s future.", location: "621 DeGraw Street Brooklyn, New York 11217", website: "http://www.fifthave.org/"},
    {name: "Palante Harlem", category: "community improvement", mission: "To reduce poverty and advocate for safe housing by organizing, educating and empowering residents. We are committed to supporting communities and to preserving our quality of life, our health, and our personal safety by assisting tenants when their rights have been violated and by holding unresponsive property owners accountable.", location: "1411 Amsterdam Avenue New York, NY 10027", website: "https://www.palanteharlem.org/"},
    {name: "Exalt", category: "Education", mission: "Exalt is designed to serve New York City’s most neglected and hard to serve youth – those involved in the criminal justice system. One of the few organizations dedicated specifically to serving court-involved youth, particularly on a voluntary basis, exalt serves teens with varying levels of justice system involvement - from a school fight that leads to a first arrest, to a young person exiting juvenile justice system placement or Rikers Island in need of recuperative services. exalt therefore acts as a prevention for deeper justice system involvement to those youth teetering on the precipice, and as a catalyst for integration into our economic mainstream for those who have already become enmeshed in the system.", location: "17 Battery Place, Suite 307 New York, New York", website: "https://exaltyouth.org/staff-profiles", twitter: "https://twitter.com/exaltyouth", instagram: "https://www.instagram.com/exaltyouthnyc/", facebook: "https://www.facebook.com/exaltyouthNYC/"},
    {name: "Marcy Lab School", category: "Education", mission: "The mission of The Marcy Lab School is to create an alternative pathway into high-growth tech careers for underrepresented and underserved youth.", location: "829 Jefferson Ave., #1R Brooklyn, NY 11221", website: "https://www.marcylabschool.org/", twitter: "https://twitter.com/marcylabschool", instagram: "https://www.instagram.com/marcylabschool/?hl=en", facebook: "https://www.facebook.com/TheMarcyLabSchool/"},
    {name: "The Knowledge House", category: "Education", mission: "The Knowledge House empowers and sustains a talent pipeline of technologists, entrepreneurs, and digital leaders, who will uplift their communities out of poverty. We are a social change organization who passionately believes that young people should be given the opportunity to succeed regardless of their financial circumstances or background. We educate, empower and mentor students, from low-income communities with the technology and workplace skills needed to build a successful career in the tech industry. Through our digital skills programs, The Knowledge House is transforming the tech industry by building an army of talented workers equipped with the latest skills needed in today’s economy.", location: "363 Rider Ave 3rd floor, The Bronx, NY 10451", website: "http://www.theknowledgehouse.org/about/", twitter: "https://twitter.com/theknowledgehou?lang=en", instagram: "https://www.instagram.com/theknowledgehouse/?hl=en", facebook: "https://www.facebook.com/theknowledgehouse/"},
    {name: "Navigate the Maze to Achievement", category: "Education", mission: "Navigate the Maze to Achievement, Inc. (NTMA) is a non-profit, educational enrichment program that prepares Black and Latino students for the Specialized High School Admissions Test and supports the students socially and academically while in high school.", website: "https://ntmanyc.org/about",facebook: "https://www.facebook.com/ntmanyc/"},
    {name: "Urban Youth Collaborative", category: "Education", mission: "Led by students, the Urban Youth Collaborative (UYC) brings together New York City students to fight for real education reform that puts students first. Demanding a high quality education for all students, our young people struggle for social, economic, and racial justice in our schools and communities.", location: "726 Broadway",website: "http://www.urbanyouthcollaborative.org/",twitter: "https://twitter.com/UYC_YouthPower?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor",instagram: "https://www.instagram.com/uycnyc/?hl=en",facebook: "https://www.facebook.com/urbanyouthcollaborative/"},
    {name: "The Audrey Lorde Project", category: "Education", mission: "The Audre Lorde Project is a Lesbian, Gay, Bisexual, Two Spirit, Trans and Gender Non Conforming People of Color center for community organizing, focusing on the New York City area. Through mobilization, education and capacity-building, we work for community wellness and progressive social and economic justice.", location: "New York, New York", website: "https://alp.org/"},
    {name: "By Us For Us", category: "Arts & Culture", mission: "BUFU is a project based collective interested in Solidarity amongst Us, co-creating with You experimental models of organizing & making generating prestige & mining time as a resource.", location: "Brooklyn, New York", website: "http://www.bufubyusforus.com/", instagram: "https://www.instagram.com/bufu_byusforus/", facebook: "https://www.facebook.com/BUFU.BYUSFORUS/?fref=ts"},
    {name: "Black Artists Network In Dialogue", category: "Arts & Culture", mission: "BADG is a global platform representing a curated collective of independent Black artists, makers, and designers across various art and design disciplines who are at the top of their respective fields.", location: "New York, NY", website: "http://band-rand.com/site/"},
    {name: "Harlem Arts Alliance", category: "Arts & Culture", mission: "HAA plays an essential role in the lives of emerging and established artists by helping build the resources, networks, and capacity of its richly diverse membership.", location: "229 West 135th Street, Front 1 New York, NY 10030 United States", website: "https://www.harlemaa.org/gallerydonate"},
    {name: "Afrotectopia", category: "Arts & Culture", mission: "AFROTECTOPIA is a social institution fostering interdiscplinary innovation at the intersections of art, design, technology, Black culture and activism.", location: "Brooklyn, NY", website: "https://www.afrotectopia.org"},
    {name: "African Diaspora International Film Festival", category: "Arts & Culture", mission: "ADIFF’s mission is to present these films to diverse audiences, redesign the Black cinema experience, and strengthen the role of African and African descent directors in contemporary world cinema.", location: "New York,NY", website: "https://nyadiff.org/spring-series-2020/about-us/"},
    {name: "Black Photographers Collective", category: "Arts & Culture", mission: "Through the new African American Photographers Annual we aim to revisit the collective process, incorporate a new generation of photographic artists, and introduce this style of photographic imagery to a new appreciative audience.", location: "Brooklyn, NY", website: "https://www.blackphotographerscollective2020.com/"},
    {name: "Black Public Media", category: "Arts & Culture", mission: "Our mission is tocommit to a fully realized expression of democracy and we accomplish this by supporting diverse voices through training, education, and investment in visionary content makers.", location: "New York,NY", website: "https://blackpublicmedia.org/"},
    {name: "Black Alliance for Just Immigration", category: "Humanities", mission: "Black Alliance for Just Immigration is a racial and migrant rights organization which engages in organizing, education, advocacy, and cross-cultural alliance building in order to end the racism, criminalization, and economic disenfranchisement of Black immigrants, refugees, and African American communities.", location: "New York,NY", website: "https://www.astraeafoundation.org/stories/black-alliance-just-immigration-baji/?gclid=Cj0KCQjwz4z3BRCgARIsAES_OVfa6W1Dc9vDiO5VuuBnnD1QE_drWCRURN9zGIK9_LmJKJkEw9uhA6caAkUjEALw_wcB"},
    {name: "BlackTech Meetup", category: "Technology", mission: "Our mission is to empower and inspire the black tech community to achieve in their careers.", location: "Brooklyn, NY", website: "http://blacktechmeetup.org/"},
]
organizations.each do |org|
  Organization.create(org)
end

projects = [
  {name: "UI Designer", description: "This role is focused on visual interactive interface design: how users interact with devices, how users process information, and ultimately how Peloton's engagement products \"look\" and \"feel\". Core to this role is the creation of the final \"pixel-perfect\" UI that Peloton Members experience, and in creating UI in a visually systematic way that ensures a holistic, consistent experience across our products.", expectations: "Manage your bandwidth and project pipeline to execute UI design in time with your team's software roadmap. Work closely and collaboratively with the UX designer. Quickly iterate and offer versions based on design critique from peers or from learnings found in user testing or feature response", timeline: "4 Weeks", team_size: 3, organization_id: Organization.first.id},
  {name: "UI Designer", description: "This role is focused on visual interactive interface design: how users interact with devices, how users process information, and ultimately how Peloton's engagement products \"look\" and \"feel\". Core to this role is the creation of the final \"pixel-perfect\" UI that Peloton Members experience, and in creating UI in a visually systematic way that ensures a holistic, consistent experience across our products.", expectations: "Manage your bandwidth and project pipeline to execute UI design in time with your team's software roadmap. Work closely and collaboratively with the UX designer. Quickly iterate and offer versions based on design critique from peers or from learnings found in user testing or feature response", timeline: "3 Months", team_size: 3, organization_id: Organization.fourth.id},
  {name: "UI Designer", description: "This role is focused on visual interactive interface design: how users interact with devices, how users process information, and ultimately how Peloton's engagement products \"look\" and \"feel\". Core to this role is the creation of the final \"pixel-perfect\" UI that Peloton Members experience, and in creating UI in a visually systematic way that ensures a holistic, consistent experience across our products.", expectations: "Manage your bandwidth and project pipeline to execute UI design in time with your team's software roadmap. Work closely and collaboratively with the UX designer. Quickly iterate and offer versions based on design critique from peers or from learnings found in user testing or feature response", timeline: "2 Weeks", team_size: 3, organization_id: Organization.find_by(name: "The Audrey Lorde Project").id},
  {name: "Full Stack Developer", description: "Seeking a Full Stack Developer with proven experience architecting and building enterprise-level applications. The individual in this role will work in small groups on various software development projects, ranging from weeks to months in duration, delivering quality solutions to our clients.", expectations: "Experience designing and building REST-based APIs. Experience with Web UI development, HTML 5, and JavaScript (Angular 1 or 2, React). Very knowledgeable in OOA/OOD and Design Patterns. Full stack development experience with one or more languages (C#, Java, or Javascript preferred).", timeline: "1 Month", team_size: 4, organization_id: Organization.fifth.id},
  {name: "Full Stack Developer", description: "Seeking a Full Stack Developer with proven experience architecting and building enterprise-level applications. The individual in this role will work in small groups on various software development projects, ranging from weeks to months in duration, delivering quality solutions to our clients.", expectations: "Experience designing and building REST-based APIs. Experience with Web UI development, HTML 5, and JavaScript (Angular 1 or 2, React). Very knowledgeable in OOA/OOD and Design Patterns. Full stack development experience with one or more languages (C#, Java, or Javascript preferred).", timeline: "6 Weeks", team_size: 3, organization_id: Organization.third.id},
  {name: "Full Stack Developer", description: "Seeking a Full Stack Developer with proven experience architecting and building enterprise-level applications. The individual in this role will work in small groups on various software development projects, ranging from weeks to months in duration, delivering quality solutions to our clients.", expectations: "Experience designing and building REST-based APIs. Experience with Web UI development, HTML 5, and JavaScript (Angular 1 or 2, React). Very knowledgeable in OOA/OOD and Design Patterns. Full stack development experience with one or more languages (C#, Java, or Javascript preferred).", timeline: "2 Weeks", team_size: 3, organization_id: Organization.first.id},
  {name: "Full Stack Developer", description: "Seeking a Full Stack Developer with proven experience architecting and building enterprise-level applications. The individual in this role will work in small groups on various software development projects, ranging from weeks to months in duration, delivering quality solutions to our clients.", expectations: "Experience designing and building REST-based APIs. Experience with Web UI development, HTML 5, and JavaScript (Angular 1 or 2, React). Very knowledgeable in OOA/OOD and Design Patterns. Full stack development experience with one or more languages (C#, Java, or Javascript preferred).", timeline: "6 Months", team_size: 2, organization_id: Organization.fourth.id},
  {name: "Web Developer", description: "Looking for a motivated web developer to join their team! Development work will vary between building and maintaining web pages, sites, and in-house applications.", expectations: "We expect experience with C#/ASP.NET, HTML, SQL. Experience with SharePoint a plus.", timeline: "4 Weeks", team_size: 1, organization_id: Organization.fourth.id},
  {name: "Web Developer", description: "Looking for a motivated web developer to join their team! Development work will vary between building and maintaining web pages, sites, and in-house applications.", expectations: "We expect experience with C#/ASP.NET, HTML, SQL. Experience with SharePoint a plus.", timeline: "5 Months", team_size: 3, organization_id: Organization.find_by(name: "Urban Youth Collaborative").id},
  {name: "Web Developer", description: "Looking for a motivated web developer to join their team! Development work will vary between building and maintaining web pages, sites, and in-house applications.", expectations: "We expect experience with C#/ASP.NET, HTML, SQL. Experience with SharePoint a plus.", timeline: "TBD", team_size: 2, organization_id: Organization.find_by(name: "African Diaspora International Film Festival").id},
  {name: "Web Developer", description: "Looking for a motivated web developer to join their team! Development work will vary between building and maintaining web pages, sites, and in-house applications.", expectations: "We expect experience with C#/ASP.NET, HTML, SQL. Experience with SharePoint a plus.", timeline: "3 Weeks", team_size: 1, organization_id: Organization.find_by(name: "The Audrey Lorde Project").id},
  {name: "Web Developer", description: "Looking for a motivated web developer to join their team! Development work will vary between building and maintaining web pages, sites, and in-house applications.", expectations: "We expect experience with C#/ASP.NET, HTML, SQL. Experience with SharePoint a plus.", timeline: "", team_size: 4, organization_id: Organization.find_by(name: "Harlem Arts Alliance").id},
  {name: "Web Desinger", description: "Candidates must have a portfolio in an accessible place or format when applying for this role.", expectations: "Create website mockups, graphics, branding and occasional marketing collateral. Design with the focus on maximizing usability and the user experience.", timeline: "3 Months", team_size: 1, organization_id: Organization.find_by(name: "Urban Youth Collaborative").id},
  {name: "Web Desinger", description: "Candidates must have a portfolio in an accessible place or format when applying for this role.", expectations: "Create website mockups, graphics, branding and occasional marketing collateral. Design with the focus on maximizing usability and the user experience.", timeline: "6 Weeks", team_size: 1, organization_id: Organization.fifth.id},
  {name: "Web Desinger", description: "Candidates must have a portfolio in an accessible place or format when applying for this role.", expectations: "Create website mockups, graphics, branding and occasional marketing collateral. Design with the focus on maximizing usability and the user experience.", timeline: "15 Weeks", team_size: 2, organization_id: Organization.fourth.id},
  {name: "Web Desinger", description: "Candidates must have a portfolio in an accessible place or format when applying for this role.", expectations: "Create website mockups, graphics, branding and occasional marketing collateral. Design with the focus on maximizing usability and the user experience.", timeline: "2 Weeks", team_size: 4, organization_id: Organization.first.id},
  {name: "Web Desinger", description: "Candidates must have a portfolio in an accessible place or format when applying for this role.", expectations: "Create website mockups, graphics, branding and occasional marketing collateral. Design with the focus on maximizing usability and the user experience.", timeline: "3 Months", team_size: 2, organization_id: Organization.find_by(name: "The Knowledge House").id},
]


projects.each do |project|
  Project.create(project)
end

puts 'done!'
